### ISSUE TITLE
Instability Travis

### ISSUE THREAD

**Issue by FreeYourSoul** [FreeYourSoul/FSeam#14]
**Describe the bug**
Travis has instability when generating the code cd /home/travis/build/FreeYourSoul/FSeam/Build-Release/test && /opt/pyenv/shims/python3 /home/travis/build/FreeYourSoul/FSeam/test/../Generator/FSeamerFile.py /home/travis/build/FreeYourSoul/FSeam/test/src/DependencyNonGettable.hh /home/travis/build/FreeYourSoul/FSeam/Build-Release/test
Traceback (most recent call last):
  File "/home/travis/build/FreeYourSoul/FSeam/test/../Generator/FSeamerFile.py", line 31, in <module>
Traceback (most recent call last):
    import CppHeaderParser
  File "/home/travis/build/FreeYourSoul/FSeam/Generator/CppHeaderParser.py", line 51, in <module>
    import ply.lex as lex
ModuleNotFoundError: No module named 'ply'
  File "/home/travis/build/FreeYourSoul/FSeam/test/../Generator/FSeamerFile.py", line 31, in <module>
    import CppHeaderParser
  File "/home/travis/build/FreeYourSoul/FSeam/Generator/CppHeaderParser.py", line 51, in <module>
    import ply.lex as lex
ModuleNotFoundError: No module named 'ply'

**To Reproduce**
1. Launch test on travis

**Comment by FreeYourSoul** [comment]
fixed
